[package]
name = "fes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

unstable_features = true

[dependencies]
streaming-iterator = "0.1.9"
regex = "1.10.2"
lazy_static = "1.4.0"
